### ISSUE TITLE
implement work-steal schedule

### ISSUE THREAD

**Issue by doomsplayer** [rustcc/coroutine-rs#10]
this is a meta issue

**Comment by doomsplayer** [comment]
cc: http://supertech.csail.mit.edu/papers/steal.pdf

**Comment by zonyitoo** [comment]
Simple implementation of *BusyLeaves*

```rust
#![feature(std_misc)]

extern crate coroutine;

use std::thread;
use std::rt::util::default_sched_threads;

use coroutine::mpmc_bounded_queue::Queue;
use coroutine::coroutine::{Coroutine, State};

fn main() {
    const MAX_MESSAGES_NUM: usize = 1000;
    let n_threads = default_sched_threads();

    let queue = Queue::with_capacity(n_threads * MAX_MESSAGES_NUM);

    let coro = Coroutine::spawn(move || {
        let mut count = 0;
        loop {
            println!("Counting {} in {:?}", count, thread::current());
            count += 1;

            Coroutine::sched();
        }
    });

    queue.push(coro);

    let mut threads = Vec::with_capacity(n_threads);
    for thread_id in 0..n_threads {
        let queue = queue.clone();
        let t = thread::Builder::new().name(format!("Thread {}", thread_id)).spawn(move || {
            loop {
                match queue.pop() {
                    Some(coro) => {
                        coro.resume().unwrap();

                        match coro.state() {
                            State::Suspended => {
                                queue.push(coro);
                            },
                            _ => {}
                        }
                    },
                    None => {}
                }
            }
        }).unwrap();

        threads.push(t);
    }

    for t in threads.into_iter() {
        t.join().unwrap();
    }
}
```

**Comment by zonyitoo** [comment]
Here comes the problem: what would happen if a `Handle` was added into the `queue` more than once? I think I should reconsider the design of APIs.

**Comment by zonyitoo** [comment]
What if two different threads got a `Handle` to the same `Coroutine` and then try to `resume` it concurrently?

There are multiple choices to apply for this situation:

1. Make the `Handle` non-Clonable. This is the most simple solution, but I am still wondering it that applicable for most situation.

2. Add a conditional variable inside the `Handle`, when the `Coroutine` is running, other thread that wants to resume this `Coroutine` may have to wait for the signal. That should be the worst solution!

**Comment by zonyitoo** [comment]
In maciekgajewski/coroutines, `Scheduler` is a Singleton. 

When the `Scheduler` was constructed, it will creates `Processor`s, which actually are native threads with work queues.

When spawning a `Coroutine`, a **Unique** handler to the `Coroutine` may be created. Then the handler will be pushed into a queue owned by `Scheduler`. So the `Scheduler` owns all `Coroutine`. 

When a `Coroutine` is ready, `Scheduler::schedule` may be called with a weak ref to the `Coroutine`, which actually adds it to a `Processor`'s work queue or a global ready queue inside the `Scheduler`.

When a `Coroutine` dies, it will tell its parent who spawns it (the `Scheduler`) to delete it. All weak ref to the `Coroutine` will be invalid.

**Comment by zonyitoo** [comment]
maciekgajewski/corotines does not provide any mechanisms to ensure only one handler to a coroutine can be added into the ready list.

**Comment by zonyitoo** [comment]
In the original version of libgreen, they implement the work-stealing scheduler heavily rely on many lock-free queues.

Every Scheduler has its own work queue, which is a lock-free queue. This queue is a special type of mpmc queue but it provides multiple `Stealer`s and one `Worker`. The Scheduler gets work from the queue with `pop` operation on the `Worker`, which is less overhead than getting data from `Stealer`. The other Schedulers have one copy of the `Stealer`. When the Scheduler is starving, it will call `steal` on every `Stealer`s it records. If one of them succeeded, it runs it immediately.

Scheduler is in thread local storage.

There are communication channels (mpsc queues) between Schedulers. They could send messages to other Schedulers.

`spawn` operation is nothing more than add the created coroutine to the Scheduler in current thread.
