### ISSUE TITLE
mioco - coroutine-rs -based mio connection handling

### ISSUE THREAD

**Issue by dpc** [rustcc/coroutine-rs#40]
Hi,

I just wanted to let you know about project using `coroutine-rs`: https://github.com/dpc/mioco , so you know you have a user there.

It narrows down to being able to handle each mio connection with a function running in per-connection coroutines, that block and unblock automatically and are scheduled quickly in userspace.

What's nice is that the performance of the simple tcp echo seem roughly the same as non-coroutine example that I played with before, and similar to libev-based tcpecho server.

Thanks!

**Comment by zonyitoo** [comment]
Oh! Thank you very much!! The mioco project is awesome!

I was trying to build a coroutine scheduler library with async I/O support, but it seems that you have already did some part of the job! That's great.

I am considering to add a multi-thread scheduler, but it may become a new crate for supporting M:N concurrent module.

I am still trying different scheduler implementations, if you are interested, [click here](https://github.com/zonyitoo/coroutine-demo). It is a demo, just a playground of mine.

Note: If you want a non-clonable `Handle`, please try this PR: https://github.com/rustcc/coroutine-rs/pull/39 . It may have better performance for context switching.

**Comment by dpc** [comment]
Oh, thanks @zonyitoo . You're code seems much broader and full.

**Comment by dpc** [comment]
Could anyone take a look and comment on: https://github.com/dpc/mioco/issues/6 ?
