### ISSUE TITLE
Getting result from coroutines

### ISSUE THREAD

**Issue by 3Hren** [rustcc/coroutine-rs#47]
Hi!

Are you planning to add an ability to extract results from finished coroutines, like it is implemented in Thread?

Something like this:
```rust
let coro = Coroutine::spawn(move || {
    42
});

let res = coro.join().unwrap();
assert_eq!(42, res);
```

**Comment by zonyitoo** [comment]
Then, what's the return type of `resume`?

**Comment by 3Hren** [comment]
Hmm, good catch. Then, this issue seems like a subset of #48.

**Comment by DenisKolodin** [comment]
With #68 it's possible:

```rust
let mut coro = Coroutine::spawn(move |me,_| {
    42
});
let result = coro.resume(0);
```
We haven't return types larger than `usize`. For custom types `pointer`s have to be used, like I do [there](https://github.com/DenisKolodin/greentask/blob/master/src/lib.rs). If we add something like `Result<T>` we'll increase overhead for coroutines which don't need results quite.

I think this issue should be closed.

**Comment by zonyitoo** [comment]
You are right.
