### ISSUE TITLE
Pushing and pulling parameters.

### ISSUE THREAD

**Issue by 3Hren** [rustcc/coroutine-rs#48]
Do you have any plans/ideas how to implement pushing and pulling parameters between coroutines?

Something like this:

 - http://www.boost.org/doc/libs/1_58_0/libs/coroutine/doc/html/coroutine/coroutine/asymmetric.html
 - http://www.boost.org/doc/libs/1_58_0/libs/coroutine/doc/html/coroutine/coroutine/symmetric.html

**Comment by zonyitoo** [comment]
I have thought about that. But have no idea how to set the lifetime gracefully.

**Comment by zonyitoo** [comment]
@3Hren Hey, take a look at this, is that meet your requirements?

https://github.com/zonyitoo/coroutine-rs/blob/boost/examples/simple.rs

**Comment by 3Hren** [comment]
Looks great, thanks!

I will test it ASAP.

**Comment by zonyitoo** [comment]
I am still looking for the way to implement symmetric coroutines.

**Comment by zonyitoo** [comment]
The latest commit have implemented asymmetric coroutines.
