### ISSUE TITLE
Stable Support

### ISSUE THREAD

**Issue by ghost** [rustcc/coroutine-rs#49]
This is probably a pipe dream. But it would be nice if this could be used on Rust stable. Has anyone investigated the work required? Is it even possible given the limitations of the current version of rust?

Obviously this pretty much used half the feature gates

``` rust
#![feature(std_misc, libc, asm, core, alloc, test, unboxed_closures, page_size, core_simd, rt)]
#![feature(rustc_private)]
#![feature(unique)]
```

I'm guessing many of these could be removed if there was some effort. But to get this compiling on rust stable you have to remove _all_ of them. So it would be useful to separate what features are are used out of convince, from what features are used because there is no other (sane) way of working around that missing feature.

The features that won't work on the current version of rust are the `asm!()` keyword used in `src/sys.rs` that could probably be removed in favour of a small c library/asm.

I haven't looked deep into this. I wanted to see if this was something that people had considered, and if so were interested in.

**Comment by zonyitoo** [comment]
Good suggestion. 

I have tried to use `asm!` to embed ASM codes inside `.rs` files, but failed...

And I am currently working on refactor this crate to have *Asymmetric Coroutines* and *Symmetric Coroutines* just like Boost in C++.

At least, `rt`, `core_simd`, `page_size`, `alloc` has to be reserved.

**Comment by canndrew** [comment]
What's the status on this? It looks like the current feature list is: `fnbox`, `asm`, `test`, `unboxed_closures`, `std_panic`, `recover`, `panic_propagate`. How many of these features are now stable or on track for stabilisation? I know `std_panic` is stable now and I think `recover` and `panic_propogate` are due to become stable. Do we actually need the other features? The `asm!` macro doesn't seem to get used anywhere for example.

**Comment by zonyitoo** [comment]
Well,

* `asm` is used in spinlock, https://github.com/zonyitoo/coio-rs/blob/master/src/sync/spinlock.rs#L41
* `std_panic`, `recover` and `panic_propagate` is going to be stablized
* `fnbox` is used for `std::boxed::FnBox`, it is required for coroutine's callback
* `test` is only used for benchmarking
* `unboxed_closures`... I have forgotten why it is required.

But yes, all those features are required.
