### ISSUE TITLE
Disable printing on stderr?

### ISSUE THREAD

**Issue by dpc** [rustcc/coroutine-rs#50]
n `mioco` we want to handle panics gracefully (eg. in tests), yet `coroutine-rs` is printing things on stderr unconditionally.

The offending line is:

https://github.com/rustcc/coroutine-rs/blob/988f7455e19be4e674a2e01d83f7429771c6bd55/src/coroutine_unique.rs#L278

Would be OK, to remove this behavior?

**Comment by zonyitoo** [comment]
Hmm, Ok. Please wait.

**Comment by zonyitoo** [comment]
#51 Is this what you want?
