### ISSUE TITLE
Broken by recent rustc nightly.

### ISSUE THREAD

**Issue by dpc** [rustcc/coroutine-rs#55]
Just pinging you that it does not compile with current nightly.

**Comment by llacroix** [comment]
Methods in `std::rt` moved to `std::sys_common` and some to `std::os`. Yet the sys module is private and methods that are needed in coroutine-rs can't be used anymore.

**Comment by zonyitoo** [comment]
Yes, indeed. What's your suggestion?

**Comment by llacroix** [comment]
Not sure if it's possible, but some methods could be reimplemented in the crate by itself. Yet there is an issue in the rust project on github to make some api in sys public instead of private.

**Comment by dpc** [comment]
My suggestion is to contact core team, and talk about it. They are very nice people and I'm sure they care about being able to express what this `coroutine-rs` is doing.

**Comment by zonyitoo** [comment]
Tracking: https://github.com/rust-lang/rust/issues/28726

**Comment by zonyitoo** [comment]
It seems that I could use `std::thread::catch_panic` to make it works right now. Please check the latest commit.

**Comment by llacroix** [comment]
Seems to be working fine. Thanks
