### ISSUE TITLE
mismatched types between `c_void` and boxed closure

### ISSUE THREAD

**Issue by izgzhen** [rustcc/coroutine-rs#59]
When compiled with nightly `rustc`, this line will report error:

```
src/asymmetric.rs:271:57: 271:74 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `Box<[closure@src/asymmetric.rs:220:23: 269:10 puller_ref:_, f:_, coro_ref:_]>`
(expected *-ptr,
    found box) [E0308]    
src/asymmetric.rs:271         coro.context.init_with(coroutine_initialize, 0, Box::new(wrapper), &mut stack);
```

I searched a bit and find a solution from [this post](http://aatch.github.io/blog/2015/01/17/unboxed-closures-and-ffi-callbacks/): change `Box::new(wrapper)` into `&wrapper as *const _ as *mut libc::c_void`

It compiled. But honestly, I am not very familiar with low-level rust so I have no idea why the `Box::new` is wrong and this casting is right.

**Comment by izgzhen** [comment]
Oh, this is still not working. I got `bus error` when trying to run `example/simple.rs`

**Comment by zonyitoo** [comment]
No, you can't. You should use `Box::into_raw(wrapper) as *const _ as *mut libc::c_void`

**Comment by izgzhen** [comment]
Not working, it doesn't typecheck :(

```
src/asymmetric.rs:271:71: 271:78 error: mismatched types:
 expected `Box<_>`,
    found `[closure@src/asymmetric.rs:220:23: 269:10 puller_ref:_, f:_, coro_ref:_]`
(expected box,
    found closure) [E0308]
src/asymmetric.rs:271         coro.context.init_with(coroutine_initialize, 0, Box::into_raw(wrapper) as *const _ as *mut libc::c_void, &mut stack);
```

Or if I first box it then `Box::into_raw`, it will still lead to runtime error

**Comment by zonyitoo** [comment]
Please refer to this one: https://github.com/zonyitoo/context-rs/blob/master/examples/asymmetric.rs

They should be almost the same. I am extremely busy these days so I am not going to fix this lately.
