### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by vi** [rustcc/coroutine-rs#61]
```
...
Build failed, waiting for other jobs to finish...
failed to run custom build command for `coroutine v0.3.2`
Process didn't exit successfully: `/home/vi/home/rust/coroutinetest/target/debug/build/coroutine-58be77db9ec74666/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unsupported architecture: i686-unknown-linux-gnu', /home/vi/home/rust/.cargo/registry/src/github.com-48ad6e4054423464/coroutine-0.3.2/build.rs:21

$ rustc --version
rustc 1.7.0-nightly (2b8e96dad 2015-12-21)
```

i686 is listed in README although.

**Comment by zonyitoo** [comment]
`coroutine-0.3.2/build.rs:21` what is that? I think you should update your repository.

**Comment by vi** [comment]
It's just a dummy `cargo new --bin` project with `coroutine = "*"` dependency added.

**Comment by vi** [comment]
Changing it to `[dependencies.coroutine]
git = "https://github.com/rustcc/coroutine-rs.git"` resolved the issue and made the example runnable.

Maybe `[dependencies]
coroutine = "*"` advice should be removed from README until some stabilisation happens?

**Comment by zonyitoo** [comment]
Oh, I see. Because I haven't uploaded the latest version to crates.io. Because this crate is still depending on many unstable Rust features. Hmm, I should remove it right now. Thanks.
