### ISSUE TITLE
Run without blocking like thread::spawn

### ISSUE THREAD

**Issue by nihiluis** [rustcc/coroutine-rs#75]
Is it possible to just execute the closure without blocking the thread waiting for it (like thread::spawn)?

cutting this essentially
```rust
    for num in coro {
        println!("{}", num.unwrap());
    }
```

**Comment by zonyitoo** [comment]
Well, what you want is a coroutine scheduler. Check [this](https://github.com/zonyitoo/coio-rs) out.

**Comment by nihiluis** [comment]
coroutines are kinda sad in rust.

**Comment by zonyitoo** [comment]
Yes. It is said. But C# style yield is going to be merged in nightly. So .. well, at least we have stackless coroutines
