### ISSUE TITLE
这个库提供的协程是像`go`一样的`有栈协程`，还是像`kotlin`一样的`有栈协程`？

### ISSUE THREAD

**Issue by loongs-zhang** [rustcc/coroutine-rs#79]

**Comment by zonyitoo** [comment]
Like Go.

**Comment by loongs-zhang** [comment]
Got it



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ty ***@***.***&gt;
发送时间: 2022年2月9日 01:46
收件人: rustcc/coroutine-rs ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [rustcc/coroutine-rs] 这个库提供的协程是像`go`一样的`有栈协程`，还是像`kotlin`一样的`有栈协程`？ (Issue #79)





 
Like Go.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cameronelliott** [comment]
Go language doesn't provide coroutines, it provides Goroutines, which are basically green threads.
Kotlin does provide coroutines, and this library provides coroutines.
So I would disagree, and say this library is more like Kotlin.
https://stackoverflow.com/a/18061564/86375
